# 基本信息
title: "八班专属博客"
name: "八班"
description: "皇家立格中的一员"
locale: "zh-CN"
url: ""
baseurl: ""
repository: "siyuan211/academicpages.github.io"
site_theme: "default"
search: true
title_separator: "-"

# 作者信息
author:
  name: "皇家立格8班"
  bio: "皇家立格中的一员"
  avatar: "profile.png"
  location: "双流区迎春路四段双流中学实验学校"
  email: "siyuanliu958@gmail.com"

# 评论设置（已关闭）
comments:
  provider: false

# 集合（collections）
collections:
  big:
    output: true
    permalink: /:collection/:path/
  thing:
    output: true
    permalink: /:collection/:path/

# 默认设置
defaults:
  # 博客文章
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  # 普通页面
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false

  # 自定义 collection: big
  - scope:
      path: ""
      type: big
    values:
      layout: single
      author_profile: true
      comments: false
      share: true

  # 自定义 collection: thing
  - scope:
      path: ""
      type: thing
    values:
      layout: single
      author_profile: true
      comments: false
      share: true

# 插件
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# 高亮
highlighter: rouge

# 输出路径格式
permalink: /:categories/:title/

# 其他输出设置
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: "\n\n"

# HTML 压缩
compress_html:
  clippings: all
  ignore:
    envs: development

# 站点地图和 RSS
atom_feed:
  hide: false
  path: # 使用默认

# 不要追踪的文件
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - package.json
  - package-lock.json
  - assets/js/plugins
  - assets/js/vendor
  - assets/js/_main.js

# 保留文件
keep_files:
  - .git
  - .svn

# 包含路径
include:
  - .htaccess
  - _pages
  - files

# 时区
timezone: Asia/Shanghai